export const SEND_CODE_VERIFICATION_REQUEST = 'SEND_CODE_VERIFICATION_REQUEST';
export const SEND_CODE_VERIFICATION_SUCCESS = 'SEND_CODE_VERIFICATION_SUCCESS';
export const SEND_CODE_VERIFICATION_FAILED = 'SEND_CODE_VERIFICATION_REQUEST_FAILED';

export const CONFIRM_CODE_REQUEST = 'CONFIRM_CODE_REQUEST';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_FAILED = 'CONFIRM_CODE_SUCCESS';

export const OPEN_CODE_FORM = 'OPEN_CODE_FORM';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_USER = 'CLEAR_USER';
