export const SEND_CODE_VERIFICATION_REQUEST = 'SEND_CODE_VERIFICATION_REQUEST';
export const SEND_CODE_VERIFICATION_SUCCESS = 'SEND_CODE_VERIFICATION_SUCCESS';
export const SEND_CODE_VERIFICATION_FAILED = 'SEND_CODE_VERIFICATION_REQUEST_FAILED';

export const CONFIRM_CODE_REQUEST = 'CONFIRM_CODE_REQUEST';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_FAILED = 'CONFIRM_CODE_SUCCESS';

export const OPEN_CODE_FORM = 'OPEN_CODE_FORM';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const FETCH_AVATAR_REQUEST = 'FETCH_AVATAR_REQUEST';
export const FETCH_AVATAR_SUCCESS = 'FETCH_AVATAR_SUCCESS';
export const FETCH_AVATAR_FAILED = 'FETCH_AVATAR_FAILED';

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILED = 'UPDATE_AVATAR_FAILED';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
